#include "app_events.hpp"

ESP_EVENT_DEFINE_BASE(LOCK_EVENT);
ESP_EVENT_DEFINE_BASE(NFC_EVENT);
ESP_EVENT_DEFINE_BASE(HK_EVENT);
ESP_EVENT_DEFINE_BASE(HW_EVENT);
ESP_EVENT_DEFINE_BASE(MQTT_EVENT);
ESP_EVENT_DEFINE_BASE(ETH_APP_EVENT);
ESP_EVENT_DEFINE_BASE(KEYPAD_EVENT);
