#pragma once
#include "esp_event.h"

ESP_EVENT_DECLARE_BASE(LOCK_EVENT);
enum {
    LOCK_STATE_CHANGED,
    LOCK_UPDATE_STATE,
    LOCK_TARGET_STATE_CHANGED,
    LOCK_OVERRIDE_STATE,
};

ESP_EVENT_DECLARE_BASE(NFC_EVENT);
enum {
    NFC_TAP_EVENT,
    NFC_STATUS_CHANGED,
};

ESP_EVENT_DECLARE_BASE(HK_EVENT);
enum {
    HK_INTERNAL_EVENT,
};

ESP_EVENT_DECLARE_BASE(HW_EVENT);
enum {
    HW_ACTION,
    HW_ALT_ACTION,
    HW_CONFIG_CHANGED,
};

ESP_EVENT_DECLARE_BASE(MQTT_EVENT);
enum {
    MQTT_STATUS_CHANGED,
};
